config/routes.rb
Rails.application.routes.draw do

	root 'instances#index'
	get 'instances/hcm', to: 'instances#index_hcm'
  resources :instances
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instance.rb
class Instance < ApplicationRecord
	validates_presence_of :isntance_name,:instace_ip,:server_user,:server_password 

	scope :contains_ESA_instance_name, -> {where("isntance_name LIKE 'ESA%'")}
	scope :contains_HCM_instance_name, -> {where("isntance_name LIKE 'HCM%'")}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  before_action :set_instance, only: [:show, :edit, :update, :destroy]

  # GET /instances
  # GET /instances.json

  def index
    @instances = Instance.contains_ESA_instance_name.paginate(:page => params[:page], :per_page => 5)
    
  end

  def index_hcm
    @instances_hcm = Instance.contains_HCM_instance_name.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /instances/1
  # GET /instances/1.json
  def show
  end

  # GET /instances/new
  def new
    @instance = Instance.new
  end

  # GET /instances/1/edit
  def edit
  end

  # POST /instances
  # POST /instances.json
  def create
    @instance = Instance.new(instance_params)

      if @instance.save
        flash[:success] = "Instance Created Successfully!" 
        redirect_to @instance 
        
      else
        render :new 
      end
    
  end

  # PATCH/PUT /instances/1
  # PATCH/PUT /instances/1.json
  def update

      if @instance.update(instance_params)
         flash[:success] = "Instance Updated Successfully!" 
         redirect_to @instance 
      else
       render :edit 
      end
    
  end

  # DELETE /instances/1
  # DELETE /instances/1.json
  def destroy
    @instance.destroy
    
      flash[:success] = "Instance Deleted Successfully!" 
      redirect_to instances_url 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instance
      @instance = Instance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instance_params
      params.require(:instance).permit(:isntance_name, :instace_ip, :server_user, :server_password, :app_user, :app_password, :db_name, :db_tns, :db_user, :db_password, :web_server_ip, :app_server_ip, :scheduler_ip, :PS_HOME, :PS_CFG_HOME, :PS_APP_HOME)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/instances/_form.html.erb
<%= form_for(instance) do |f| %>
  <%= render 'shared/error_message' %>
  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :isntance_name %>
      <%= f.text_field :isntance_name, class: "form-control input-sm" %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :instace_ip %>
      <%= f.text_field :instace_ip, class: "form-control input-sm" %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :server_user %>
      <%= f.text_field :server_user,class: "form-control input-sm" %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :server_password %>
      <%= f.text_field :server_password,class: "form-control input-sm" %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :web_server_ip %>
      <%= f.text_field :web_server_ip,class: "form-control input-sm" %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :app_server_ip %>
      <%= f.text_field :app_server_ip,class: "form-control input-sm" %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :scheduler_ip %>
      <%= f.text_field :scheduler_ip,class: "form-control input-sm" %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :PS_HOME %>
      <%= f.text_field :PS_HOME,class: "form-control input-sm" %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :PS_CFG_HOME %>
      <%= f.text_field :PS_CFG_HOME,class: "form-control input-sm" %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :PS_APP_HOME %>
      <%= f.text_field :PS_APP_HOME,class: "form-control input-sm" %>
    </div>


    <div class="form-group col-md-4">
      <%= f.label :app_user %>
      <%= f.text_field :app_user, class: "form-control input-sm" %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :app_password %>
      <%= f.text_field :app_password,class: "form-control input-sm" %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :db_name %>
      <%= f.text_field :db_name,class: "form-control input-sm" %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :db_user %>
      <%= f.text_field :db_user,class: "form-control input-sm" %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :db_password %>
      <%= f.text_field :db_password,class: "form-control input-sm" %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :db_tns %>
      <%= f.text_area :db_tns,class: "form-control" %>
    </div>

    <div class="col-md-10 form-group">
      <%= submit_tag "Submit", class: "btn btn-primary" %>
    </div>
  </div> 
<% end %>

app/views/instances/edit.html.erb
<div class="row">
	<div class="col-md-6">
		<h1>Editing Instance</h1>
	</div>
	<div class="col-md-3 col-md-offset-3">
		<%= link_to 'Back', @instance, class: "btn btn-primary" %>
	</div>
</div>
<%= render 'form', instance: @instance %>

app/views/instances/index.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>ESA Instances</h1>
  </div>
  <div class="col-md-3 col-md-offset-3">
    <%= link_to 'New Instance', new_instance_path, class: "btn btn-primary pull-right" %>
  </div>
</div>
<table class="table table-striped table-bordered table-hover table-responsive">
  <thead>
    <tr>
      <th>Isntance name</th>
      <th>Instace ip</th>
      <th>Server user</th>
      <th>Server password</th>
      <th>App user</th>
      <th>App password</th>
      <th>DB name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @instances.each do |instance| %>
      <tr>
        <td><%= instance.isntance_name %></td>
        <td><%= instance.instace_ip %></td>
        <td><%= instance.server_user %></td>
        <td><%= instance.server_password %></td>
        <td><%= instance.app_user %></td>
        <td><%= instance.app_password %></td>
        <td><%= instance.db_name %></td>
        <td><%= link_to 'Show', instance, class: "btn btn-info btn-xs" %></td>
        <td><%= link_to 'Edit', edit_instance_path(instance), class: "btn btn-warning btn-xs" %></td>
        <td><%= link_to 'Destroy', instance, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @instances %>

app/views/instances/index_hcm.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>HCM Instances</h1>
  </div>
  <div class="col-md-3 col-md-offset-3">
    <%= link_to 'New Instance', new_instance_path, class: "btn btn-primary pull-right" %>
  </div>
</div>

<table class="table table-striped table-bordered table-hover table-responsive">
  <thead>
    <tr>
      <th>Isntance name</th>
      <th>Instace ip</th>
      <th>Server user</th>
      <th>Server password</th>
      <th>App user</th>
      <th>App password</th>
      <th>DB name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @instances_hcm.each do |instance| %>
      <tr>
        <td><%= instance.isntance_name %></td>
        <td><%= instance.instace_ip %></td>
        <td><%= instance.server_user %></td>
        <td><%= instance.server_password %></td>
        <td><%= instance.app_user %></td>
        <td><%= instance.app_password %></td>
        <td><%= instance.db_name %></td>
        <td><%= link_to 'Show', instance, class: "btn btn-info btn-xs" %></td>
        <td><%= link_to 'Edit', edit_instance_path(instance), class: "btn btn-warning btn-xs" %></td>
        <td><%= link_to 'Destroy', instance, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @instances_hcm %>

app/views/instances/new.html.erb
<h1>New Instance</h1>

<%= render 'form', instance: @instance %>

<%= link_to 'Back', instances_path %>

app/views/instances/show.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title"><strong>Server Details</strong></h3>
      </div>
      <div class="panel-body">
        <p>
          <strong>Instace ip:</strong>
          <%= @instance.isntance_name %>
        </p>
        
        <p>
          <strong>Instace ip:</strong>
          <%= @instance.instace_ip %>
        </p>

        <p>
          <strong>Server user:</strong>
          <%= @instance.server_user %>
        </p>

        <p>
          <strong>Server password:</strong>
          <%= @instance.server_password %>
        </p>

        <p>
          <strong>Web Server IP:</strong>
          <%= @instance.web_server_ip %>
        </p>

        <p>
          <strong>App Server IP:</strong>
          <%= @instance.app_server_ip %>
        </p>

        <p>
          <strong>Scheduler IP:</strong>
          <%= @instance.scheduler_ip %>
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title"><strong>DB Details</strong></h3>
      </div>
      <div class="panel-body">
        <p>
        <strong>Db name:</strong>
        <%= @instance.db_name %>
        </p>

        <p>
        <strong>Db user:</strong>
        <%= @instance.db_user %>
        </p>

        <p>
        <strong>Db password:</strong>
        <%= @instance.db_password %>
        </p>

        <strong>TNS Details:</strong>
        <textarea rows="2">  
          <%= @instance.db_tns %>
        </textarea>

      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title"><strong>Misc..</strong></h3>
      </div>
      <div class="panel-body">
        <p>
        <strong>PS Home:</strong>
        <%= @instance.PS_HOME %>
        </p>

        <p>
        <strong>Configuration Home:</strong>
        <%= @instance.PS_CFG_HOME %>
        </p>

        <p>
        <strong>APP Home:</strong>
        <%= @instance.PS_APP_HOME %>
        </p>

        <p>
        <strong>Application User:</strong>
        <%= @instance.app_user %>
        </p>

        <p>
        <strong>Application password:</strong>
        <%= @instance.app_password %>
        </p>

      </div>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_instance_path(@instance), class: "btn btn-primary btn-sm" %> |
<%= link_to 'Back', instances_path, class: "btn btn-primary btn-sm" %>

app/views/layouts/_footer.html.erb
<div class="footer">
    <h3>Compass PSADMIN - A Community that works together.</h3>
    <p class="copyright">Copyright © 2018.Designed and built with all the love in the world by <a href="https://twitter.com/morapost" target="_blank">@BHUSHAN.<span class="second-line">All Rights Reserved.</span> </p>
  </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "COMPASS PSADMIN",root_path,class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "ESA Instance",root_path %></li>
        <!-- <a href="#">Home <span class="sr-only">(current)</span></a></li> -->
        <li><%= link_to "HCM Instance", instances_hcm_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Contact Us<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">PSADMIN-DBACOGNIZANT@cognizant.com</a></li>
            <li><a href="#">bhushan.manoharan@cognizant.com</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compass PSADMIN Instace Details</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Compass PSADMIN Instance Details">
    <meta name="author" content="Bhushan - working for cognizant">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Exo+2:500" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <div id="wrap">
		  <%= render 'layouts/navbar'%>
		  <div class="container">
		  	<% flash.each do |key, value| %>
		    	<div class="alert alert-<%= key %>"><%= value %></div>
		    <% end %>
		    <%= yield %>
		  </div> 
		</div>  
	<%= render 'layouts/footer' %>
		
  </body>
</html>

app/views/shared/_error_message.html.erb
<% if @instance.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@instance.errors.count, "error") %>.
    </div>
    <ul>
    <% @instance.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>